import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/layout/Header";
import "./globals.css";
import Footer from "@/components/layout/footer/Footer";
import NewsletterSection from "@/components/layout/footer/widgets/NewsLetter";
import NewsLatter from "@/components/layout/footer/widgets/NewLatter";
import FeatureCards from "@/components/layout/footer/widgets/FeaturedCard";
// import ReduxProviders from "@/redux/ReduxProvider";
import Hero from "@/components/layout/Hero";
import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shop you & Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ReduxProviders> */}
        <Navbar />
        <Hero />
        <Header />
        {children}
        <NewsLatter />
        <FeatureCards />
        <Footer />
        {/* </ReduxProviders> */}
      </body>
    </html>
  );
}
