import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/layout/Header";
import "./globals.css";
import Footer from "@/components/layout/footer/Footer";
import NewsletterSection from "@/components/layout/footer/widgets/NewsLetter";
import FeatureCards from "@/components/layout/footer/widgets/FeaturedCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <NewsletterSection />
        <FeatureCards />
        <Footer />
      </body>
    </html>
  );
}
